version: '3.8'

services:
  postgres:
    image: postgres
    container_name: paseos-db
    ports:
      - "2222:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paseos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
