version: '3.8'

services:
  postgres:
    image: postgres
    container_name: paseos-db
    ports:
      - "2222:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paseos
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: perro-paseos-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: >
      - sh -c "npx prisma migrate deploy && npm run start:prod"


volumes:
  postgres_data:
