version: '3.8'

services:
  postgres:
    image: postgres
    container_name: paseos-db
    ports:
      - "2222:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paseos
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: perro-paseos-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/paseos"
    depends_on:
      - postgres

volumes:
  postgres_data:
